keys:
  - &admin_pieterp age1hdktq9ega9lcv0ula8ew9s9tmh7ndpkhyj0v2atmagnlh395aaus04hxwg
  - &server_ideapad age154mjp28j3kqj8hnaszzfdfkqp25uyt7cz9rdev9c7wzp23yhzswqcapvkq
  - &server_nixberry age1qf5jjqefdmz8v3gjxlm9zlzq740cu3l2tqjknrwkkfj367kxt5mslxry7h
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_pieterp
      - *server_ideapad
      - *server_nixberry
