# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos-root";
    fsType = "ext4";
    options = [ "noatime" ];
  };


  # NOTE: wanted to do this:
  #
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-label/BOOT";
  #   fsType = "vfat";
  #   options = [ "noatime" ];
  # };
  #
  # fileSystems."/nix" = {
  #   device = "/dev/disk/by-label/nixos-nix";
  #   fsType = "ext4";
  #   options = [ "noatime" ];
  # };

  swapDevices = [
    # NOTE: wanted to do this
    #
    # { device = "/dev/disk/by-label/nixos-swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
