
name: Flake check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ./.github/workflows/setup-nix.yml
      - run: nix flake check
      

      
