name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup-nix.yml
  update-sops-keys:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - run: pre-commit run --all-files

